### ISSUE TITLE
Support for ARM64v8

### ISSUE THREAD

**Issue by lag-linaro** [YOURLS/docker-yourls#11]
Having just built and tested this repo, it is my pleasure to report that this project *just works* on ARM64v8.

I would be happy to send a pull-request enabling it in Docker Images - with your blessing of course.

**Comment by LeoColomb** [comment]
Thanks a lot for your report @lag-linaro! Glad to know this compatibility!

> send a pull-request enabling it in Docker Images

Sure! Which changes are required?

**Comment by lag-linaro** [comment]
We need to change [this file](https://github.com/docker-library/official-images/blob/master/library/yourls) to add an 'Architectures' label.

**Comment by lag-linaro** [comment]
Pull request submitted: #12
