### ISSUE TITLE
docker container doesn't start after resetting the container

### ISSUE THREAD

**Issue by paradeiser** [YOURLS/docker-yourls#114]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

I was running 1.8.1 as docker container hosted on a Synology NAS without any issues.

After the update to 1.8.2 (downloaded new image "latest" and made a container reset with the new image)
I get the following error log in the console:
```
Warning: Undefined array key 1 in Standard input code on line 8

[Tue Sep 07 12:36:07.003192 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator
```

### Expectation

Usually I just reset and restart the container with the new version and all systems are up and running.

### Context

Host is running DSM 7.0-41890
DB is external

**Comment by LeoColomb** [comment]
Could you provide:
* The exact image you are using
* How did you configured it
* Apache HTTPD version

**Comment by LeoColomb** [comment]
X-Ref:
* https://stackoverflow.com/questions/66617147/how-to-fix-38function-not-implemented-ah00141-could-not-initialize-random-n
* https://askubuntu.com/questions/1323305/apache-commands-failing-with-ah00141-could-not-initialize-random-number-genera
* https://github.com/docker-library/wordpress/issues/630

**Comment by paradeiser** [comment]
Image:
yourls               1.8.1     46036a25929e   3 days ago     481MB
(There is also an older image with the ID 640128b65eb7)

nginx version: nginx/1.17.10

It's a Synology DSM 7.0-41890, so I guess it's a customized Linux dist.

On another machine (a DSM 6.2.4-25556), the same config is running just fine. Like it also did before on the DSM 7.0 

```
{
   "cap_add" : [],
   "cap_drop" : [],
   "cmd" : "apache2-foreground",
   "cpu_priority" : 10,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "entrypoint_default" : "docker-entrypoint.sh",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "PHPIZE_DEPS",
         "value" : "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c"
      },
      {
         "key" : "PHP_INI_DIR",
         "value" : "/usr/local/etc/php"
      },
      {
         "key" : "APACHE_CONFDIR",
         "value" : "/etc/apache2"
      },
      {
         "key" : "APACHE_ENVVARS",
         "value" : "/etc/apache2/envvars"
      },
      {
         "key" : "PHP_EXTRA_BUILD_DEPS",
         "value" : "apache2-dev"
      },
      {
         "key" : "PHP_EXTRA_CONFIGURE_ARGS",
         "value" : "--with-apxs2 --disable-cgi"
      },
      {
         "key" : "PHP_CFLAGS",
         "value" : "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
      },
      {
         "key" : "PHP_CPPFLAGS",
         "value" : "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
      },
      {
         "key" : "PHP_LDFLAGS",
         "value" : "-Wl,-O1 -pie"
      },
      {
         "key" : "GPG_KEYS",
         "value" : "XXXXXX XXXXXX"
      },
      {
         "key" : "PHP_VERSION",
         "value" : "8.0.2"
      },
      {
         "key" : "PHP_URL",
         "value" : "https://www.php.net/distributions/php-8.0.2.tar.xz?a=1"
      },
      {
         "key" : "PHP_ASC_URL",
         "value" : "https://www.php.net/distributions/php-8.0.2.tar.xz.asc?a=1"
      },
      {
         "key" : "PHP_SHA256",
         "value" : "XXXXXXXXX"
      },
      {
         "key" : "YOURLS_VERSION",
         "value" : "1.8"
      },
      {
         "key" : "YOURLS_SHA256",
         "value" : "XXXXXXXXX"
      },
      {
         "key" : "YOURLS_DB_NAME",
         "value" : "XXX"
      },
      {
         "key" : "YOURLS_PASS",
         "value" : "XXX"
      },
      {
         "key" : "YOURLS_USER",
         "value" : "XXX"
      },
      {
         "key" : "YOURLS_DB_PASS",
         "value" : "XXX"
      },
      {
         "key" : "YOURLS_DB_USER",
         "value" : "XXX"
      },
      {
         "key" : "YOURLS_DB_HOST",
         "value" : "mysql.XXX.tld"
      },
      {
         "key" : "YOURLS_SITE",
         "value" : "https://url.XXX.tld"
      }
   ],
   "exporting" : false,
   "id" : "XXX",
   "image" : "yourls:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 31457280,
   "memory_limit_slider" : 30,
   "name" : "yourls-1.8",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 80,
         "host_port" : 8301,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : []
}

```
Execution Command: docker-entrypoint.sh apache2-foreground

Probably it's a Synology issue. Sorry for bothering you.

Thanks for your help,
paradeiser

**Comment by LeoColomb** [comment]
As far as I understand, this seems very tied to DSM, indeed.
I recommend subscribing to the following issue to gather recommendation and potential fixes: https://github.com/docker-library/wordpress/issues/630

I'm closing this issue in favor of the mentioned one.
