### ISSUE TITLE
Comparison for boolean variables in configuration is still faulty

### ISSUE THREAD

**Issue by thechristschn** [YOURLS/docker-yourls#22]
The last attempt to fix variable comparison for environment variables in the configuration file in https://github.com/YOURLS/docker-yourls/commit/71832c631cd4cb174070d54d3136aa2e413edee8 doesn't work for booleans which have `true` as default value.

For example
`define( 'YOURLS_UNIQUE_URLS', filter_var(getenv('YOURLS_UNIQUE_URLS'), FILTER_VALIDATE_BOOLEAN) ?: true );`
will always evaluate to true, even if `getenv('YOURLS_UNIQUE_URLS')` is false.

Because if set to false, the statement would be:
`define( 'YOURLS_UNIQUE_URLS', false ?: true );`
which results in true.

The fix would be to delete the comparsion, because the filter will always return `true` or `false`. For example:
`define( 'YOURLS_UNIQUE_URLS', filter_var(getenv('YOURLS_UNIQUE_URLS'), FILTER_VALIDATE_BOOLEAN));`

**Comment by LeoColomb** [comment]
Indeed, good catch. Thanks!
Would you like to open a PR with the fix?

**Comment by thechristschn** [comment]
I just realized, that my proposed fix would also remove the default values if the variable is not set. But I will think of another fix and create a PR.

**Comment by LeoColomb** [comment]
> would also remove the default values if the variable is not set

Indeed too. 😆 

Sure for the PR, thanks!

**Comment by LeoColomb** [comment]
X-Ref: #21
