### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by gerroon** [YOURLS/docker-yourls#25]
Hi

Can you  add some help about how to reverse proxy it with Apache? 

thanks

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @gerroon.

What do you mean by adding some help?
Have you see the Apache httpd documentation as well as Docker documentation?

**Comment by gerroon** [comment]
I mean sample reverse proxy settings for apache to make it easier for non experts.

**Comment by LeoColomb** [comment]
@gerroon OK, but this is not specific to YOURLS neither Docker, right?
You should prefer official and/or generic documentation, specially when related to a Docker-based server. There are tons of this kind of documentation on the web.
