### ISSUE TITLE
Cannot serve directory

### ISSUE THREAD

**Issue by Franselbaer** [YOURLS/docker-yourls#27]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
** + Reproduce instructions **

* I installed latest Yourls Docker Image.
* Followed the Instructions.
* Added Hostname to my Frontend Nginx Proxy
* Ran /admin/install.php successfully
* Added an example URL
* Gone to that url (https://shorturl.treide.org/1)
* Got 403

Inspected .htaccess file and played around with it but haven't got it to work.
It looks like it is not 100% fitting for the reverse proxy case. But I couldn't get
it how to bring it to work.

**Expected behavior**
After setting up a new Docker container it is expected that basic functionality is working out of the box.

**Actual behavior**
Running into 403

**Screenshots**

![snap](https://user-images.githubusercontent.com/11044625/57614458-9999d900-7579-11e9-8cba-91bf03d11ac2.png)

**Versions**
Docker 18.06-ce
Ubuntu 16.04

**Additional context**

**Comment by Franselbaer** [comment]
Nevermind.

``` 
proxy_set_header X-Forwarded-.....
``` 

Adding proper headers seems to be the solution. 

Thank You

**Comment by madleech** [comment]
Also note that `/` doesn't serve anything; you need to go to `/admin` to actually get a healthy page. Worth nothing if you're using a health check.
