### ISSUE TITLE
Add environment variable for configuring YOURLS_NOSTATS

### ISSUE THREAD

**Issue by vitalyzhakov** [YOURLS/docker-yourls#29]
Hello!

**Summary**
Our installation of short link must serve about 1,1 millions of links per month.
I see big log table after stress testing.

I decide disable stats in db to decrease heavy load.

**Describe the solution you'd like**
In basic yourls config we may set this option, https://github.com/YOURLS/YOURLS/blob/master/includes/Config/Config.php#L196-L198, but in docker image - not.
I want to configure this option by environment variable.

**Comment by LeoColomb** [comment]
Thanks @vitalyzhakov for this report!

Do you mount the volume? If so, I would prefer to suggest editing your own `config.php`.

**Comment by vitalyzhakov** [comment]
@LeoColomb , hello!
For high avaliability we start at least 2 container instance in one datacenter (docker swarm). It does not have any volumes, all configuration changes by environment variables.
