### ISSUE TITLE
docker yourls error

### ISSUE THREAD

**Issue by WeiKKJ** [YOURLS/docker-yourls#31]
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message

**Comment by LeoColomb** [comment]
Thanks for this report, @WeiKKJ.
That said this error is relative to Apache httpd, not YOURLS, and is actually a warning you can ignore (httpd should continue to run).
See also https://stackoverflow.com/a/46267809
