### ISSUE TITLE
Docker version deprecated?

### ISSUE THREAD

**Issue by Plausible0Bug** [YOURLS/docker-yourls#32]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

**To Reproduce**
Go to https://hub.docker.com/_/yourls
Find stack.yml demo section
Deploy to PWD

**Expected behavior**
Yourls should be deployed to play with docker

**Actual behavior**
Configuration broken or not working

**Screenshots**
![image](https://user-images.githubusercontent.com/46285962/62824263-4f6cc780-bb69-11e9-9277-b64e83976f24.png)

**Versions**
tag: latest

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Plausible0Bug** [comment]
Nevermind this program is impossible to deploy without setup real domain first.

**Comment by LeoColomb** [comment]
Thanks for this report, @Plausible0Bug.
Don't forget the first path you need to visit is `http://domain/admin/install.php`.
You may need to specify the host used with the `YOURLS_SITE` env variable.
