### ISSUE TITLE
Fresh docker-compose install only shows "403 Forbidden"

### ISSUE THREAD

**Issue by mmoehrlein** [YOURLS/docker-yourls#35]
If i start the docker container with docker-compose on my own system or by using the pwd button on the dockerhub registry page and then try to access with localhost:8080 or ip:8080 i always get a 403 Forbidden page.

This should be the relevant part of the logs from my system

```
yourls_1  | [Tue Nov 05 13:48:39.499502 2019] [autoindex:error] [pid 23] [client 138.246.2.73:38506] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
yourls_1  | 138.246.2.73 - - [05/Nov/2019:13:48:39 +0000] "GET / HTTP/1.1" 403 496 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
```

not providing more info about my system since it also fails on pwd. if systeminfo still is needed im happy to provide it.

**Comment by vitalyzhakov** [comment]
@mmoehrlein , hello!
403 on main page is correct behaviour.

Go `/admin` page to install application.

**Comment by mmoehrlein** [comment]
@vitalyzhakov thanks for the reply. Maybe an additional line on the Docker hub readme might be helpfull. This one did not make it clear to go to /admin 🙈:

> Then, access it via http://localhost:8080 or http://host-ip:8080 in a browser.

going to close since this seems like the solution and i cant try it atm or in the next days.

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @mmoehrlein.m, and thanks for the reply @vitalyzhakov!

Indeed, the root url does not contain any content by default.
We will fix the docs soon.

**Comment by whalehub** [comment]
@LeoColomb The docs still say

> Then, access it via http://localhost:8080 or http://host-ip:8080 in a browser.

as of today.

**Comment by LeoColomb** [comment]
@whalehub Indeed, thanks for the head-up.

https://github.com/docker-library/docs/pull/1648
