### ISSUE TITLE
Cannot acces withou enter "index.php" on url

### ISSUE THREAD

**Issue by leonardoborlot** [YOURLS/docker-yourls#39]
I´ve instale with Docker using a stack. When I try to access, the response is:

Forbidden
You don't have permission to access this resource.

Apache/2.4.38 (Debian) Server at vdon.us Port 80

But, when I place the https://domain.com/index.php its work very good. 

This is a bug or there any thing to correct this?

Deploy from Docker Stack
 container_name: yourls_vdon_us
  image: yourls:latest
  ports: 
     - "8103:80"
  restart: always
  volumes:
     - yourls_vdon_us:/var/www/html
  environment:
      YOURLS_SITE: https://vdon.us

* [ ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
What actually happens.

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by LeoColomb** [comment]
Hello @leonardoborlot.

By default YOURLS instance doesn't have any content at root.
You must start on `domain/admin/index.php`.
