### ISSUE TITLE
Update image to PHP 7

### ISSUE THREAD

**Issue by J0WI** [YOURLS/docker-yourls#4]

**Comment by LeoColomb** [comment]
Yeap!

**Comment by LeoColomb** [comment]
Do you think I should drop php5.6 or we need to keep both?

**Comment by LeoColomb** [comment]
Oh, I see you're working on it. Please don't loose your time with rebasing, I will manage to merge your 72 branch and keep all your work if you open a PR. :)

**Comment by J0WI** [comment]
Do users relay on a specific PHP version (e.g. due plugin support etc.)?

**Comment by LeoColomb** [comment]
I don't think so. And as YOURLS with Docker is new and not massively used, it should be safe to skip php5 support.

**Comment by LeoColomb** [comment]
> `You don't have permission to access / on this server`

Before installation, it may be possible that `/` returns a error. You must install first, by accessing `/admin/`.
