### ISSUE TITLE
The gmp or bcmath extension must be installed to read this database

### ISSUE THREAD

**Issue by chrisXmz** [YOURLS/docker-yourls#40]
Hello all,
## Basic install armv7 (Raspberry Pi 4) issue
I run YOURLS on a Raspberry Pi 4 with buster and this docker image.
after installing and running the image I got this issue:  

## Issue
```
Fatal error: Uncaught RuntimeException: The gmp or bcmath extension must be installed to read
 this database.
 in /var/www/html/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php:295 ... 
```
## Workaround from me:
Enter into the container:
`docker exec  -it <YOURLS-Container-Name> /bin/bash`
Enter
`docker-php-ext-install bcmath`  
Stop and Restart the Container `docker stop ...` and `docker start ...`

## Question for a Fix
Can you please insert the needed php module into the docker image?

best regards
Chris

**Comment by LeoColomb** [comment]
Hello @chrisXmz, thanks for your report.

Looks like a really interested case.
Do you know if big integers are managed differently on armv7 than amd64?

> The MaxMind DB format includes 128-bit unsigned integer as a type. Although no MaxMind-distributed database currently makes use of this type, both the pure PHP reader and the C extension support this type. The pure PHP reader requires gmp or bcmath to read databases with 128-bit unsigned integers.
>
> https://github.com/maxmind/MaxMind-DB-Reader-php/tree/febd4920bf17c1da84cef58e56a8227dfb37fbe4#128-bit-integer-support

I would try to avoid adding extensions the the common Docker image to keep the size low.

**Comment by chrisXmz** [comment]
Hello @LeoColomb, I‘m not shure about how PHP is using this integers. But I have used this official image and an image of ‘arm32v7/yourls’. Bouth images are with the same behavior. After docker container is up and running , I can access admin interface but on using the link shortener, I got this php error message. That is really strange. 
I think, if we would really keep Raspberry Pi up and running with this wonderful application. This module has to add. 
I’m sorry if this answer is not so detailed about the issue itself. I have not enough skills about php and the modules, in this case. 
But I hope you can insert the needed module into the official image (for arm architectures) to get YOURLS to work for the small group of Raspberry users. :-)
Best regards Chris.

**Comment by vitalyzhakov** [comment]
@chrisXmz , hello!

Can you extend `arm32v7/yourls` with install proper extension or make pull request?

**Comment by JamieWhite** [comment]
Ive bumped into the same issue too. Thanks for the workaround @chrisXmz

**Comment by jimbobcraig** [comment]
thanks also for the workaround @chrisXmz
