### ISSUE TITLE
Remove VOLUME from DOCKERFILE

### ISSUE THREAD

**Issue by bkief** [YOURLS/docker-yourls#41]
**Summary**
I am trying to build a down stream image using `FROM yourls` and include a front end. The issue is that new files copied to /var/www/html are not persisted after the build because the directory is designated as a volume. I'd like to propose removing this from the DOCKERFILE and just let users define volumes at runtime.

**Motivation**
Allows customization of yourls website in other docker environments

**Is your feature request related to a problem? Please describe.**
Users cannot use and customize yourls docker containers

**Describe the solution you'd like**
Remove the `VOLUME /var/www/html` from the docker template

**Comment by LeoColomb** [comment]
Hello @bkief, thanks for opening this ticket.

Please see #36

**Comment by vitalyzhakov** [comment]
@LeoColomb , hello!
If we link new issue to #36 , may be you reopen #36 ?

**Comment by LeoColomb** [comment]
We'll continue the discussion on #36.
