### ISSUE TITLE
NGINX Config issue

### ISSUE THREAD

**Issue by LordVaderXIII** [YOURLS/docker-yourls#42]
Hi Guys

Im have some issues with My NGINX config. 
Im getting this error in the YOURLS log
`Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

Im running on Unraid and using the letsencrypt docker that contains NGINX. This is my config
`server {
	
	listen 443 ssl;
    listen [::]:443 ssl;

    server_name url.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
	
	root /config/www/YOURLS;
    index index.php index.html index.htm;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        include /etc/nginx/fastcgi_params;
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_unraid url;
        proxy_pass http://192.168.86.41:8088;
    }
}`

Im getting this issue when I try my shortened links. I get the Forbidden page. 

Can anyone help please?

**Comment by LeoColomb** [comment]
Thanks for opening this @LordVaderXIII.
That said, is it related with Docker? There isn't any relation with Nginx in this repo...

**Comment by LordVaderXIII** [comment]
> Thanks for opening this @LordVaderXIII.
> That said, is it related with Docker? There isn't any relation with Nginx in this repo...

Yes I am using the docker image then I am reverse proxying it behind nginx. I was wondering if anyone had some suggestions on how to get it working.

**Comment by LeoColomb** [comment]
Like any other docker image! 🙂 
You may use fpm variant to use Nginx upstream severs, after that nothing special.
Do you have a error output or a log?

**Comment by LordVaderXIII** [comment]
Thanks @LeoColomb Im not sure what FPM is. Im not all that well versed in NGINX. 

I think my issue is specific to the  fact that Im running Unraid with the Letsencrypt docker and the YOURLS docker.

**Comment by vitalyzhakov** [comment]
Hello, @LordVaderXIII !

You may run nginx with ssl terminating outside yourls docker container.

So, traffic scheme may be `host nginx` -> `docker yourls`.
Or, `container with nginx with SSL terminating` -> `docker yourls`.

**Comment by LeoColomb** [comment]
Thanks @vitalyzhakov, that advice is a good one.
I recommand also any reading on how to play with Nginx and WordPress docker image. Just replace WordPress with YOURLS (and match the settings of course).
Eg. https://www.howtoforge.com/tutorial/dockerizing-wordpress-with-nginx-and-php-fpm/
