### ISSUE TITLE
YOURLS_TABLE_PREFIX not functional

### ISSUE THREAD

**Issue by ksarnelli** [YOURLS/docker-yourls#45]
Settings the environment variable YOURLS_TABLE_PREFIX via docker has no impact on the container.  It always defaults to 'yourls_' as the table prefix.  I also tried setting an environment variable for YOURLS_DB_PREFIX (matching what is in the sample config file in case the docker container documentation is incorrect) and it works as expected.

Running YOURLS v1.7.6 via https://hub.docker.com/_/yourls/

**Comment by LeoColomb** [comment]
Thanks for your report @ksarnelli.
That's actually normal, because the environment variable you're looking for is `YOURLS_DB_PREFIX`.

But indeed documentation on the Docker Hub is wrong! That is a really good catch.
I'll fix it soon.

**Comment by ksarnelli** [comment]
Thanks - I actually prefer no table prefix. Is this possible with the current docker version?

I'm migrating from a standard install to the docker container and it looks like the container is set to always use 'yourls_' when the environment variable is blank.  The non-container version defaults to blank.

**Comment by LeoColomb** [comment]
> The non-container version defaults to blank.

I'm afraid you're wrong! 😄 

https://github.com/YOURLS/YOURLS/blob/c43e9237005f50ded9796f5f5da058182c50dad7/user/config-sample.php#L27

> I actually prefer no table prefix

I totally understand and even agree, but we can't change the default behavior without break a lot of database already in use.
This update will probably come in next major release.

**Comment by ksarnelli** [comment]
I probably worded that wrong.  I meant the standard version supports (not defaults to) a blank table prefix :)
Doesn't look like there is a way to currently do this with the docker without the pull request I just submitted.

**Comment by ksarnelli** [comment]
I totally see your point regarding breaking existing installs.  Maybe a workaround would be an additional environment variable 'YOURLS_DB_USE_TABLE_PREFIX' (bool) that defaults to true.  If you accept this approach I can submit a pull request.

**Comment by LeoColomb** [comment]
@ksarnelli Adding a new variable is something I would try to avoid.
I suggest you link the volume with you own config file where you can tweak everything.

**Comment by LeoColomb** [comment]
Closing as per https://github.com/docker-library/docs/pull/1662
