### ISSUE TITLE
Support YOURLS_FLOOD_DELAY_SECONDS in config-docker.php

### ISSUE THREAD

**Issue by ksarnelli** [YOURLS/docker-yourls#47]
Please add support for setting YOURLS_FLOOD_DELAY_SECONDS in config-docker.php via an environment variable. Thanks!

**Comment by LeoColomb** [comment]
@ksarnelli Adding a new variable is something I would try to avoid.
I suggest you link the volume with you own config file where you can tweak everything.

**Comment by ksarnelli** [comment]
Thanks...I actually didn't realize that a regular config file would take precedence over the config-docker file.  I just mapped the user folder and copied my config over from my non-docker install and now everything works again.
