### ISSUE TITLE
expose YOURLS_ADMIN_SSL to the config file

### ISSUE THREAD

**Issue by blbradley** [YOURLS/docker-yourls#48]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Configure YOURLS_ADMIN_SSL inside a container

**Motivation**
HTTPS everywhere

**Describe the solution you'd like**
some config file edits

**Describe alternatives you've considered**
Rolling my own image

**Comment by LeoColomb** [comment]
See https://github.com/YOURLS/docker-yourls/pull/49#issuecomment-604115946
