### ISSUE TITLE
There is no option to define TZ based Offset in the Docker image

### ISSUE THREAD

**Issue by elicro-rimon** [YOURLS/docker-yourls#59]
**Summary**
In a regular yourls there is a plugins which allows the admin to define TZ based offset.
Like America/Los_Angeles etc...:
https://github.com/YOURLS/timezones

Can it be added into the docker image?

The basic OFFSET Hours doesn't work for places which have summer and winter time.

I was thinking of creating a separate Docker container image.

**Comment by LeoColomb** [comment]
Hi @elicro-rimon, thanks for opening this ticket.

> Can it be added into the docker image?

You can add everything you want into the docker image, as if it was a raw YOURLS install.
Just create a volume on `/var/www/html/user` to customize your setup.

> I was thinking of creating a separate Docker container image.

Definitely as you prefer, up to you! 🙂
