### ISSUE TITLE
Broken entrypoint

### ISSUE THREAD

**Issue by J0WI** [YOURLS/docker-yourls#8]
The image does not work for me and just throws the following error:
> Warning: mysqli::__construct(): (HY000/2002): No such file or directory in Standard input code on line 17
> MySQL Connection Error: (2002) No such file or directory

Even if I'm using the given [example](https://github.com/YOURLS/docker-yourls#-via-docker-stack-deploy-or-docker-compose) and linking both containers together. I also tried to pass all database environment variables directly.

**Comment by LeoColomb** [comment]
This seems to be a problem with ``

Does the following code (line 17) is working for you?
```php
list($host, $socket) = explode(':', getenv('YOURLS_DB_HOST'), 2);
```

**Comment by LeoColomb** [comment]
Actually it should not.
Maybe `localhost` resolution. What if you change in the `config-docker.php`:

```php
define( 'YOURLS_DB_HOST', getenv('YOURLS_DB_HOST') ?: '127.0.0.1' );
```

**Comment by J0WI** [comment]
Nope :confused:

**Comment by LeoColomb** [comment]
It should:
* With name resolution I [get `No such file or directory`](https://travis-ci.org/YOURLS/docker-yourls/jobs/389892463#L962) like you.
* With a direct IP and no resolution, [the error is `Connection refused`](https://travis-ci.org/YOURLS/docker-yourls/jobs/389929092#L1007) which is expected. ([the change](https://github.com/YOURLS/docker-yourls/commit/4f107fe4b6e1ad8883dbea53ef1a745ecd642539))

Are you sure environnement variables used to handle MySQL connection are well provided?

**Comment by J0WI** [comment]
It works now if all ENVs are explicitly set.

**Comment by LeoColomb** [comment]
Yep, OK, that's quite intended I think. 😇 
I'm closing this issue since entrypoint is "working".
But I'm sure there are better ways to manage env variables (but I don't know them right now), so please feel free to open another issue or even a PR if you find one of these ways.

Thanks again for your feedback and followup! 🙏
