### ISSUE TITLE
.htaccess file is missing in all images

### ISSUE THREAD

**Issue by gurumark** [YOURLS/docker-yourls#9]
Hi,
.htaccess file is missing in all images resulting in 404 in redirects. I had to copy it manually to get it work.

In addition, I got invalid gateway error in all images except apache which works fine.
thanks.

**Comment by LeoColomb** [comment]
> In addition, I got invalid gateway error in all images except apache which works fine.

I think in all cases these errors/issues come from the lack of server configuration (such as `.htaccess`).

Would you aim to open a PR to add some server configs? Thx! 👍

**Comment by ChrisRo89** [comment]
I created a PR for it: https://github.com/YOURLS/docker-yourls/pull/10
